# Generated by Django 5.1.2 on 2024-10-24 09:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_remove_balasan_vote_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='balasan',
            name='tanggal_balasan',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forum',
            name='tanggal_posting',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vote',
            name='nilai',
            field=models.IntegerField(default=0),
        ),
    ]
