# Generated by Django 5.1.2 on 2024-10-25 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_rename_tanggal_balasan_balasan_tanggal_posting'),
    ]

    operations = [
        migrations.AddField(
            model_name='balasan',
            name='vote',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
