# Generated by Django 5.1.2 on 2024-10-25 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_rename_vote_balasan_nilai_vote'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set(),
        ),
    ]
