# Generated by Django 5.1.2 on 2024-10-22 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makanan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kategori',
            name='makanan',
        ),
        migrations.AddField(
            model_name='kategori',
            name='makanan',
            field=models.ManyToManyField(related_name='kategori', to='makanan.makanan'),
        ),
    ]
