# Generated by Django 5.1.2 on 2024-10-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makanan', '0002_remove_kategori_makanan_kategori_makanan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kategori',
            name='makanan',
        ),
        migrations.AddField(
            model_name='makanan',
            name='kategori',
            field=models.ManyToManyField(related_name='makanan', to='makanan.kategori'),
        ),
    ]
