# Generated by Django 5.1.2 on 2024-10-22 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restoran', '0002_restoran_gambar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restoran',
            name='jam_operasional',
        ),
        migrations.AddField(
            model_name='restoran',
            name='jam_buka',
            field=models.TimeField(default='08:00'),
        ),
        migrations.AddField(
            model_name='restoran',
            name='jam_tutup',
            field=models.TimeField(default='22:00'),
        ),
    ]
